import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Next-final -- codeevolution",
    template: "%s | codeevolution",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <header className='bg-slate-400 text-black py-6 text-center font-semibold text-3xl'>
          <p>Header</p>
        </header>
        <div className='min-h-[calc(100vh-200px)]'>{children}</div>
        <header className='bg-slate-500 text-black py-6 text-center font-semibold text-3xl'>
          <p>Footer</p>
        </header>
      </body>
    </html>
  );
}
